Lint and format docs
Point72/csp pull request #136
Opened 2024-03-06 17:05 UTC by pavithraes

Fixes #135

2024-03-06 17:41 UTC, timkpaine requested changes
Can you edit the commit message from `Re-push updates with signed commits` to something descriptive of the change itself, e.g. `Add docs linting/fixing`.

2024-03-06 17:41 UTC, timkpaine commented on Makefile
> +	mdformat docs/wiki/ README.md examples/README.md
`lint-docs` should be:
- `python -m mdformat --check`
- `python -m codespell_lib <omit --write>`

Then seperately, add `fix-docs` and add to `fix` target.

2024-03-06 19:13 UTC, pavithraes commented
Thanks for the review, I've made the necessary updates :)

2024-03-06 21:15 UTC, timkpaine requested changes

2024-03-06 21:15 UTC, timkpaine commented on pyproject.toml
> +    "mdformat",
these probably need to be added to the `dev-environment.yml` conda env too @ngoldbaum

2024-03-06 21:54 UTC, ngoldbaum commented
It doesn’t exist already but it might be nice to have a linting subsection in the dev guide, explaining what is linted with what tools and with a pointer toward `make fix`.

2024-03-06 21:55 UTC, timkpaine commented
> It doesn’t exist already but it might be nice to have a linting subsection in the dev guide, explaining what is linted with what tools and with a pointer toward `make fix`.

Feel free to add more to the [existing lint and fix section](https://github.com/Point72/csp/blob/main/docs/wiki/98.-Building-From-Source.md#lint-and-autoformat)

2024-03-06 21:57 UTC, ngoldbaum commented
Oops, forgot that was in the build instructions.

2024-03-06 21:58 UTC, timkpaine commented
Also the [contributing guidelines](https://github.com/Point72/csp/blob/main/docs/wiki/98.-Building-From-Source.md#contributing) should be moved to the 99 developer page as they include required information (like e.g. closing PRs with non-substantive changes or without prior discussion for big features). But we can do in a followup PR to avoid conflicts

2024-03-06 22:04 UTC, timkpaine submitted a review, later dismissed
3 followup changes:

- [x] Add these 2 new deps to conda yaml
- [x] Move contributing guidelines from 98 to 99
- [x] Expand 98 linting/fixing docs and link from 99

2024-03-07 15:20 UTC, ngoldbaum approved these changes

2024-03-07 15:20 UTC, merged