Draft of mkdocs setup
Point72/csp pull request #198
Opened 2024-04-17 16:27 UTC by melissawm

Will allow **local** documentation set up with `mkdocs serve --clean` 

Also fixes a few broken links resulting from the documentation restructure.

2024-04-19 14:34 UTC, robambalu approved these changes

2024-04-19 15:06 UTC, timkpaine requested changes
Hey, this breaks the wiki so I don't think it was tested (I don't see a wiki on your fork).

Here is an example on my fork: https://github.com/timkpaine/csp/wiki

Click e.g. "Install csp" and you'll see the linking is now broken.
<img width="250" alt="Screenshot 2024-04-19 at 11 06 15" src="https://github.com/Point72/csp/assets/3105306/4ea6908b-407e-4492-9c58-3a03dd961f2d">

2024-04-19 17:47 UTC, melissawm commented
Thanks for letting me know @timkpaine , this is still in draft as I figure out these issues, I'll make sure to fix. Cheers!

2024-07-21 14:25 UTC, timkpaine commented
Closing as stale, we can revisit down the road

2024-07-21 14:25 UTC, closed without merging